server {
    listen 80;
    server_name 192.168.50.4;

    root /www/wwwroot/xueguan-admin;
    index index.html;
    client_max_body_size 32m;

    location /api/ {
        proxy_pass http://127.0.0.1:8080/api/;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }

    access_log /www/wwwlogs/xueguan-admin.log;
    error_log  /www/wwwlogs/xueguan-admin.error.log;
}
